### ISSUE TITLE
ProductsAttribsRaw, include manufacturer's name

### ISSUE THREAD

**Issue by osaw0405** [lat9/dbio#136]
Would be nice to have ability to include additional fields such as manufacturer or categories to enable better data filtration when changing attribute details.

**Comment by lankeeyankee** [comment]
Sorry, that was me, logged into my son's account.  :-)

**Comment by lat9** [comment]
I'm not sure I understand the request.  Are you asking that additional fields be included in the `export` to make it easier to determine which attributes should be assigned?

**Comment by lankeeyankee** [comment]
Yes, that's what I mean. I understand it would need info pulled from another table and I don't know if this is possible. But, to be able to match the model number to a manufacturer or category(ies) would greatly help in filtering through the sheet. Because this is a great sheet to bulk change option value prices, and to be able to isolate certain ranges of products based on filter criteria/custom DBIO templates would be a great boost in cutting through what could be thousands of line items in the sheet.

**Comment by lat9** [comment]
Adding the manufacturer's name will be fairly easy, but the categories will be a PITA; is that an acceptable compromise?

**Comment by lankeeyankee** [comment]
Sure, I think adding any additional filter would be very helpful for stores with products with attributes
